### ISSUE TITLE
phoneGap Build support

### ISSUE THREAD

**Issue by elzahaby** [dpa99c/cordova-plugin-firebasex#105]
# Feature request

I tried for many hours to get this plugin to work with the use of phonegap build service but it just doesnt work so i hope somehow that somebody adds support for phonegap build, or could explain me how i could make it work

The problem is not in building the source code but once i launch the app on device nothing happens, i mean it works perfectly fine but the Firebase Funcionality just seems to not work at all ( i am trying to get Cloud Messaging to work)

**Comment by luisjs** [comment]
I'm having (sort of) the same problem, using cli-9.0.0, and specifying resource-file in my config.xml manually (due to the lack of hooks in PGB). The build would be successful, but nothing would happen in the app.

However, I've noticed in the build logs (and later via Chrome debugging) that the plugin wasn't being included at all, because it thought I was using cli-7.1.0.

```
Installing "cordova-plugin-firebasex" at "6.0.7" for android  
Plugin doesn't support this project's cordova version. cordova: 7.1.0, failed version requirement: >=9  
Skipping 'cordova-plugin-firebasex' for android
```

Do you have the same message in the logs? I found a similar report to mine in the Adobe forums, but no replies yet.

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-plugin-firebasex#phonegap-build) this plugin will not work with Phonegap Build because it relies on [Cordova hook scripts](https://cordova.apache.org/docs/en/latest/guide/appdev/hooks/) which are [not supported by Phonegap Build](https://github.com/phonegap/build/issues/425)
