### ISSUE TITLE
Firebase/Firestore

### ISSUE THREAD

**Issue by sengoontoh** [dpa99c/cordova-plugin-firebasex#190]
Any chance we will get full-fledged realtime and firestore capabilities through these native libraries? The Javascript version of firestore are just not up to task due to their dependence on IndexedDB.

**Comment by dpa99c** [comment]
Firestore support was added in v8.1.0

**Comment by sengoontoh** [comment]
Sweet! Any way of adding hooks to update events?

**Comment by dpa99c** [comment]
Do you mean [Realtime listeners](https://firebase.google.com/docs/firestore/query-data/listen)?
I had considered implementing them initially but it is not simple because I'd need to manage a map of the JS callback to the native listener. This could be added as an additional feature but would take some time.
