### ISSUE TITLE
How to disable Push Notifications?

### ISSUE THREAD

**Issue by ojordan0** [dpa99c/cordova-plugin-firebasex#205]
Hi,

I'm working on an Ionic4 project, and building for iOS, Android and Windows platforms. After installing the plugin, which I use for Analytics and Crashlytics, the iOS project automatically activated the Background Mode "Remote notifications" in the Capabilities tab. When I build the project and submit the build, I get an email from the Apple Store saying: 

_ITMS-90078: Missing Push Notification Entitlement - Your app appears to register with the Apple Push Notification service, but the app signature's entitlements do not include the "aps-environment" entitlement. ......_

Is there a way to deactivate Push Notifications in the plugin? I don't use this feature and I don't plan to, so I don't want to modify the Prov. Profiles for the App; just need to disable it.

Thanks!!

**Comment by dpa99c** [comment]
This plugin is a fork of [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase) which is a monolithic plugin implementing all aspects of the Firebase SDK, including push notifications.
To modularise it in order to use specific parts of the SDK would be a large job and so not in the scope of maintaining this fork.

If you wish to only use specific parts of the Firebase SDK, I suggest using the series of plugins by @chemerisuk such as [cordova-plugin-firebase-analytics](https://github.com/chemerisuk/cordova-plugin-firebase-analytics).

**Comment by ojordan0** [comment]
Thank you for your answer. I perfectly understand. 

Thanks!

**Comment by kjellouli** [comment]
@ojordan0 
You can use this https://stackoverflow.com/questions/44568009/how-to-disable-push-notification-capability-in-xcode-project to disable push notifications on a free Apple developer acconut
