### ISSUE TITLE
iOS error when using both Firebasex and Local Notifications: "FirebasePlugin[native]: willPresentNotification: aborting as not a supported UNNotificationTrigger"

### ISSUE THREAD

**Issue by AndrewBargan** [dpa99c/cordova-plugin-firebasex#230]
**Current behavior:**

We're using cordova-plugin-local-notifications and cordova-plugin-firebasex plugins in our ionic 3 project. When iOS app is in foreground and scheduled local notification should appear it throws 
error "FirebasePlugin[native]: willPresentNotification: aborting as not a supported UNNotificationTrigger" instead
I've created minimal ionic 3 project here https://github.com/AndrewBargan/firebasexAndLocalNotificationsBug

Take a look at src/pages/home/home.ts for code that causes problem.

**Expected behavior:**

Subscription handlers to both firebasex and local notificaitons work simultaneously.

**Steps to reproduce:**

When app from repository mentioned above built and installed on a real device:
- Connect Safari to device
- Open console and keep it open
- Click "Grant Permissions to Notifications"
- Click "Schedule Notification in 3 sec"

In 3 seconds error is thrown to console:
"FirebasePlugin[native]: willPresentNotification: aborting as not a supported UNNotificationTrigger"

<img width="610" alt="Screenshot 2019-11-19 at 13 43 23" src="https://user-images.githubusercontent.com/33483711/69143883-b6880980-0ad2-11ea-8113-38208467c133.png">

To reproduce this bug again you need to remove platform and add plugins once again and rebuild the project. For this:

- Remove installed test app from the iPhone
- Run: ionic cordova platform rm ios && rm -r plugins && rm -r platforms && ionic cordova platform add ios
- Set valid app signing profile in xCode
- Run: ionic cordova build ios -- --buildFlag="-UseModernBuildSystem=0" && ionic cordova run ios --device

Keep in mind you have to put valid GoogleService-Info.plist into the root of the project to make app work.

**Environment information**
- Cordova CLI version
       - 9.0.0 (cordova-lib@9.0.1)

- Cordova platform version
      ios 5.0.1
  Available platforms: 
      android ^8.0.0
      browser ^6.0.0
      electron ^1.0.0
      osx ^5.0.0
      windows ^7.0.0

- Plugins & versions installed in project
cordova-plugin-androidx 1.0.2 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.0 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebasex 7.0.1 "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

- Dev machine: macOS 10.15.1
        
- Device details: iPhone SE, iOS 13.2.2

- XCode v11.2.1

BTW: Found issue that looks similar: https://github.com/dpa99c/cordova-plugin-firebasex/issues/95
If it is maybe a good idea to pull from fork of this plugin with the fix that Fabricio Garcia did to the current one.

**Comment by dpa99c** [comment]
The problem is that both [this plugin](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/AppDelegate%2BFirebasePlugin.m#L311) and [`cordova-plugin-local-notifications` implements](https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/ios/APPLocalNotification.m#L479) the same `UNUserNotificationCenterDelegate willPresentNotification` delegate and since delegates have a 1:1 relationship with their parent class, only one of the delegates is being called - in this case, the `cordova-plugin-firebasex` delegate in response to the notification created by `cordova-plugin-local-notifications`.
`cordova-plugin-firebasex` is correctly ignoring a notification which it didn't create so doesn't know how to present (`aborting as not a supported UNNotificationTrigger`) however the `cordova-plugin-local-notifications` delegate is not being called because only 1 delegate was invoked, hence you don't get a notification.

This is a conflict between the two plugins (see [this SO post](https://stackoverflow.com/questions/12774808/multiple-delegates-in-ios) for further info about multiple delegates) .
In a native iOS app, you'd simply combine both into a single delegate however due to the nature of Cordova plugins, this isn't a feasible solution.

The best solution would be implement a common shared delegate which broadcast an event which both plugins could add observers for, meaning both plugins would receive the notification event.
However this would require a rework of both plugins and coordination to create/use/maintain such a common component.

Therefore this isn't something that's an easy bugfix and I'm unlikely to attempt to fix this in the near future.
I deem this to be a caveat of using this plugin rather than a bug with it since it functions correctly in isolation and only encounters an issue when another plugin is introduced which makes use of the same native delegates.

FYI I see no commits in [the repo](https://github.com/Steffaan/cordova-plugin-local-notifications) in the [issue you referenced](https://github.com/dpa99c/cordova-plugin-firebasex/issues/95) but please feel free to point out if I have missed that particular piece of code.

**Comment by AndrewBargan** [comment]
Hey @dpa99c,

Thanks for you quick answer!
That's sad. At least good to mention this caveat in the docs that this plugin isn't working in conjunction with local notifications plugin.

Thanks!
Have a good day!

**Comment by dpa99c** [comment]
Related to this in #443: I believe to resolve this issue, both this plugin and `cordova-plugin-local-notification` will need to take a different approach to register for app delegate events so they don't conflict.
A possible solution is to extend [cordova-plugin-app-event](https://github.com/katzer/cordova-plugin-app-event) to support the necessary delegates that both plugins can share which should resolve their conflict.
I will investigate the viability of this solution.

**Comment by golyo** [comment]
> I will investigate the viability of this solution.

Hi @dpa99c !

The problem is the same with release 11.0.1-cli. 
"FirebasePlugin[native]: willPresentNotification: aborting as not a supported UNNotificationTrigger"

Could you give me advice how to use it, with cordova-plugin-local-notification plugin ?

Thanks!

**Comment by dpa99c** [comment]
@golyo due to the nature of the conflict between this plugin and `cordova-plugin-local-notification` (both implementing a global delegate method that must be unique) there is no easy solution.
Either you'd need to manually rewrite the native iOS implementation to merge the two implementations or implement an interstitial handler such as I've described above. This is a viable approach but will take considerable effort and also will require changes to both this plugin and `cordova-plugin-local-notification` to make it work.

**Comment by BradCB** [comment]
I hope this helps:

I am using https://github.com/katzer/cordova-plugin-local-notifications version: 0.9.0-beta.3 and https://github.com/wizpanda/cordova-plugin-firebase-lib version: 5.1.1 both are working on iOS. I can fire off background/foreground local and remote notifications.

**Comment by souly1** [comment]
Hey @dpa99c , any update about this?
Given this plugin 'swallows' the event so that it cannot be handled elsewhere can't it instead be passed on to same event handler here with a warning or or perhaps a configurable flag, instead of ignoring notification?

**Comment by BradCB** [comment]
The new updates to cordova-plugin-firebasex seems to have reintroduced a conflict. I am still getting local notifications when the app is fully closed and when the app is in the background but not when the app is in the foreground. 

Nothing in APPLocalNotification.m or AppDelegate+FirebasePlugin.m is triggering a breakpoint in Xcode when the app is in the foreground and should be showing a local notification. 

Remote notifications are still working for all three states.

**Comment by jircdev** [comment]
Could someone solve this problem? Any solution from some plugin?

**Comment by miguelp25** [comment]
Still having the same problem...

**Comment by TheNotorius0** [comment]
I had this problem too, and I resolved with this code:

```
    FirebasePlugin.onMessageReceived(function (message) {

        console.log('message', message);

        if (currentPlatform === Platforms.iOS && message.meta && message.meta.plugin === 'cordova-plugin-local-notification-12') {

            return;
        }

        if (message.tap === 'background') {

            return;
        }

        if (message.notification_type === 'notification_queue') {

            ...
        }
        ...
 });
```
When you receive a **foreground** notification from the local-notification-plugin, you can see it in the **message.meta.plugin** property. 

Since I don't need to handle data when my local notification triggers (I already do it inside the app in other ways), I just return, but you can do your custom logic there I guess.

PS: note that I'm using cordova-plugin-local-notification-12, but you can change it with the plugin you're using
