### ISSUE TITLE
getValue API is incompatible with firebase plugin but change is not documented

### ISSUE THREAD

**Issue by N0ps32** [dpa99c/cordova-plugin-firebasex#283]
I'm trying to migrate from the legacy firebase plugin to firebasex, however the APP I'm working on leverages RemoteConfiguration, we use the getValue function with the namespace parameter as described in: https://github.com/arnesson/cordova-plugin-firebase/blob/master/docs/API.md#getvalue

However firebasex doesn't offer a namespace parameter, how should we migrate? Can we just delete the namespace and everything will continue working?

**Comment by dpa99c** [comment]
This is because all namespaced methods were removed in the Firebase SDK on [Android v17.0.0](https://firebase.google.com/support/release-notes/android#remote-config_v17-0-0):

> Removed all namespace methods.

And deprecated in [iOS v6.3.0](https://firebase.google.com/support/release-notes/ios#version_630_-_june_19_2019):

> All Remote Config API which take an explicit namespace parameter are deprecated.

Therefore the `cordova-plugin-firebase` implementation is out-of-date with respect to the method signatures of the latest Firebase SDK versions.

So you should remove the namespaces as they are no longer supported by Firebase.
