### ISSUE TITLE
iPhone 8 and Iphone 8 Plus, not receiving notifications in background mode

### ISSUE THREAD

**Issue by alidaniel** [dpa99c/cordova-plugin-firebasex#306]
iPhone 8 and Iphone 8 Plus, does not receive notifications in background mode; The plugin works well with other apple models such as iPhone 6 or iPhone XR; Androis also work ok

**Comment by dpa99c** [comment]
AFAIK there's no logical reason why notifications would work on some iPhones and not others - APNS is entirely software based so unrelated the hardware on which it's running.
Is it possible that you are testing with a development provisioning profile which does not have APNS capabilities set for the UDIDs of those specific devices?
Please test using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your APNS configuration.

Closing as I don't believe there's any possibility of a code bug in this plugin that could cause this, however if you are able to prove otherwise, I'm happy to reopen it.
