### ISSUE TITLE
iOS Foreground Notifications stop working after app restart

### ISSUE THREAD

**Issue by sprengerst** [dpa99c/cordova-plugin-firebasex#307]
Hi,

I set up APNS and background + foreground notifications started to work both :) 

After a while, when the app is in background or the app is killed from task manager manually in iOS, if I restart the app I don't get any foreground notifications anymore. I have to deinstall and install the app from scratch again to receive foreground notifications again.

Background notifications are still working. But foreground is not. This happens only in the iOS variant. :( 

Does anybody have any ideas?

Best,
Stefan

**Comment by sprengerst** [comment]
If I revoke the permission in iOS Settings, my app tries to grant permission again and the foreground notifications are received again. But the next time I kill the app, the game starts again.

**Comment by sprengerst** [comment]
[inc.together.social] Received remote notification request D33B-F206 [ hasAlertContent: 1, hasSound: 0 hasBadge: 0 hasContentAvailable: 0 hasMutableContent: 0 ]

Seems taht the notification is received, but it is not shown anymore.

**Comment by dpa99c** [comment]
Can you confirm you are specifying `"notification_foreground": "true"` in the FCM message payload's data section as outlined in the [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#foreground-notifications)?

If so, please can you test using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and its built-in FCM client and confirm whether you can reproduce the issue in this known codebase.

For example:

    npm run-script send -- --token="<your_device_token>" --message=notification.json

Since [notification.json](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/notification.json) contains the required key for foreground notifications.

**Comment by dpa99c** [comment]
Closed due to no response

**Comment by sprengerst** [comment]
I found the solution. The firebasex plugin clashes with the local-notifications plugin from ionic. If you enable both of this cordova plugins in an Ionic project, you have the explained buggy behaviour. I solved it by removing the local Notificafions plugin. I tried this with ionic 4 and 5. @dpa99c
