### ISSUE TITLE
Cordova vue ios does not trigger grant permission to receive notification

### ISSUE THREAD

**Issue by wenj5335** [dpa99c/cordova-plugin-firebasex#314]
# Bug report

**Current behavior:**
Android works properly but iOS does not ask permission for notification setting.

**Expected behavior:**

iOS device fresh install should be prompt to ask notification setting.

**Steps to reproduce:**

**Screenshots**

**Environment information**

- Cordova CLI version 
	- cordova 9
- Cordova platform version
	- `cordova platform ls`
- Plugins & versions installed in project (including this plugin)
   
![image](https://user-images.githubusercontent.com/50609315/75224730-01a56d00-57e4-11ea-85a2-ecfe569fae76.png)

- Dev machine OS and version, e.g.
    - OSX
        - `sw_vers`
    - Windows 10
        - `winver`
        
_Runtime issue_
- Device details
    - _e.g. iPhone X, Samsung Galaxy S8, iPhone X Simulator, Pixel XL Emulator_
- OS details
    - _e.g. iOS 12.2, Android 9.0_	
	
_Android build issue:_	
- Node JS version
    - `node -v`
- Gradle version
	- `ls platforms/android/.gradle`
- Target Android SDK version
	- `android:targetSdkVersion` in `AndroidManifest.xml`
- Android SDK details
	- `sdkmanager --list | sed -e '/Available Packages/q'`
	
_iOS build issue:_
- Node JS version
    - v13.9.0
- XCode version
    -  v11.3.1

**Related code:**
```
insert any relevant code here such as plugin API calls / input parameters
```
![image](https://user-images.githubusercontent.com/50609315/75224820-3285a200-57e4-11ea-86b5-28781348d60a.png)
![image](https://user-images.githubusercontent.com/50609315/75224868-4e894380-57e4-11ea-8065-662b1ab26251.png)
![image](https://user-images.githubusercontent.com/50609315/75224925-75477a00-57e4-11ea-84b3-7d1373c40e60.png)

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here

```

</details><br/><br/>

**Other information:**

**Comment by wenj5335** [comment]
I found the workaround which is straight using Firebaseplugin.grantPermission on device ready inside cordovaApp

**Comment by vesper8** [comment]
@wenj5335 Hi there, I'm building an hybrid Vue app with vue-cli and https://github.com/m0dch3n/vue-cli-plugin-cordova and am now trying to use this plugin to add FCM push notifications. I am really struggling and could really use a little bit of help with getting this going.

I'd like to know where you got your start, I'm having a look at your code snippets above and am wondering if you followed a tutorial or came up with all of it yourself? I'm puzzled as to what is `f7` for example.

Since you seem to be doing something similar.. also using Vue and this plugin, is there any chance we could connect so I can ask you some questions?

Anything would help.

Many thanks

**Comment by wenj5335** [comment]
Hi @vesper8. Previously I have been build the hybrid app using vanilla js with the frontend framework call Framework7. Now I had migrated the whole framework to the same frontend framework but using vue method which call Framework-vue.  [https://framework7.io/vue/](url)

I have just follow how the documentation stated and applied in the vue way.
