### ISSUE TITLE
Cordova missing Module

### ISSUE THREAD

**Issue by TdoubleG** [dpa99c/cordova-plugin-firebasex#316]
# Bug report

**Current behavior:**
When running `cordova build ios` following error appears

```
> cordova build ios
cordova-plugin-firebasex: Preparing Firebase on iOS
Cannot find module '../../src/plugman/platforms/ios'

```

I removed my platforms and plugin dir to build a fresh ios version. After running `cordova build ios` the 

**Expected behavior:**

The build should run successfully

**Steps to reproduce:**

Make a fresh `cordova build ios` with the current plugin version v8.0.1

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- ` ios 5.1.1`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
```
ProductName:    Mac OS X
ProductVersion: 10.15.3
BuildVersion:   19D76
```

	
_iOS build issue:_
- Node JS version
    - `v10.16.3`
- XCode version
   -`Version 11.3.1 (11C504)`

**Comment by dpa99c** [comment]
This error does not arise from this plugin, which makes no reference to such a file, however it has the appearance of doing so since it appears following the console log message generated by this plugin.
I suggest running `cordova build ios --verbose` to find the cause.

You can validate that this plugin works correctly in isolation by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test).

**Comment by TdoubleG** [comment]
Indeed, seems that "cordova-plugin-universal-link" was the problem. Thank you anyway :)
