### ISSUE TITLE
Firebase Analytics setScreenName not working

### ISSUE THREAD

**Issue by TdoubleG** [dpa99c/cordova-plugin-firebasex#317]
# Bug report

**Current behavior:**

Hello, I'm experiencing some issues while collecting analytical data. 
I'm using Ionic v5.x
 
When calling `this.firebaseX.setScreenName('AnyScreenName')` following error appears in Xcode console

`[Firebase/Analytics][I-ACS031000] Ignoring call to setScreenName:screenClass:. Screen reporting is disabled.`

Analytics Collection is enabled. I can't even see the reporting in google analytics nor in firebase.

**Expected behavior:**

The screen reporting should collect information and show in google analytics and firebase

**Steps to reproduce:**

Install the plugin, write the code to set the screen name, build for ios, watch the xcode console output

**Screenshots**

**Environment information**

- Cordova CLI version 
	- `9.0.0 (cordova-lib@9.0.1)`
- Cordova platform version
	- ` ios 5.1.1`
- Plugins & versions installed in project (including this plugin)
    - `cordova plugin ls`
- Dev machine OS and version, e.g.
    - OSX
```
ProductName:    Mac OS X
ProductVersion: 10.15.3
BuildVersion:   19D76
```
     
**Related code:**
```
    this.firebase.setScreenName('screenName');
```

**Console output**
<details>
<summary>console output</summary>

```

// Paste any relevant JS/native console output here
2020-02-26 08:48:46.979065+0100 appName[19556:4954651] 6.17.0 - [Firebase/Analytics][I-ACS031000] Ignoring call to setScreenName:screenClass:. Screen reporting is disabled.
```

</details><br/><br/>

**Other information:**

**Comment by dpa99c** [comment]
Had a look at this and - as stated in [this SO answer](https://stackoverflow.com/a/46916247/777265) - and I've confirmed this empirically - setting `FirebaseScreenReportingEnabled=false` in the app plist (which is what setting the plugin variable `FIREBASE_ANALYTICS_COLLECTION_ENABLED=false` does) permanently disables screen reporting in the build - both automatic and manual.

However, with some testing, I've discovered that even if `FirebaseScreenReportingEnabled=true`, if `FIREBASE_ANALYTICS_COLLECTION_ENABLED=false` is set in the Google plist, then screen events are not sent. So I'll remove the setting of `FirebaseScreenReportingEnabled` since it is not necessary.
