### ISSUE TITLE
iOS Problem with auth0 from v.8.0.0

### ISSUE THREAD

**Issue by stegithub** [dpa99c/cordova-plugin-firebasex#332]
Hi,
i've update plugin to latest version, then downgrade to 8.0.1 due to https://github.com/dpa99c/cordova-plugin-firebasex/issues/326.
Then i encountering some issue (infinite pending login) with auth0 login (cordova plugin and auth0-js). I don't understand the issue but only downgrading to v.7.0.2 it continue to works like before i update.
Does anyone think of what it can be related to?

**Comment by dpa99c** [comment]
There is insufficient information here to diagnose an issue but the cause is most likely a conflict between auth0 and the Firebase Auth functionality added to this plugin in v8.

Unfortunately I'm unable to provide support for resolution of each and every plugin conflict as there are too many possible causes but you can validate that this plugin works correctly in isolation by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)

**Comment by stegithub** [comment]
> There is insufficient information here to diagnose an issue but the cause is most likely a conflict between auth0 and the Firebase Auth functionality added to this plugin in v8.
> 
> Unfortunately I'm unable to provide support for resolution of each and every plugin conflict as there are too many possible causes but you can validate that this plugin works correctly in isolation by building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)

Ok, thanks anyway. Maybe someone else has encountered this problem. Thanks for your work.
