### ISSUE TITLE
[Android] Badge in app icon still display although I overrides the badge option in default channel

### ISSUE THREAD

**Issue by pptrexvn** [dpa99c/cordova-plugin-firebasex#338]
I put this code when deviceready is fired
```
FirebasePlugin.setDefaultChannel({
      id: 'some_default_channel_id',
      name: 'some_default_channel_name',
      badge: false
    }, console.log, console.log);
```
When run the app, I found the `some_default_channel_name` in notification setting, but after I push a notification to this device (in background), the Badge number still be shown.

This issue happened on:
Android 10
Cordova 8.0.0
cordova-plugin-firebasex 7.0.2
Samsung and XiaoMi device

Are there any other ways to remove this badge number after receiving a push notification?

Thanks.

Updated: I also pulled this project to my local and build my self (https://github.com/dpa99c/cordova-plugin-firebasex/tree/7.0.2), then I changed these lines of code to force hide badge number

[FirebasePlugin.java#L1178](https://github.com/dpa99c/cordova-plugin-firebasex/blob/7.0.2/src/android/FirebasePlugin.java#L1178)

From
```
channel.setShowBadge(badge);
```
to
```
channel.setShowBadge(false);
```

And add `.setNumber(0)` to notificationBuilder

[FirebasePluginMessagingService.java#L208](https://github.com/dpa99c/cordova-plugin-firebasex/blob/7.0.2/src/android/FirebasePluginMessagingService.java#L208)

But the badge still shows and counts the push notification.

**Comment by dpa99c** [comment]
The plugin is [setting the badge visibility on Android](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePlugin.java#L1826) in the way described in [the Android documentation](https://developer.android.com/training/notify-user/badges#disable), i.e. calling `setShowBadge()` when creating a channel.

However, on testing on an Pixel 2 running Android 10, I can confirm that setting `channel.setShowBadge(false)` in the Java (which is the same as `FirebasePlugin.setDefaultChannel({id: 'my_channel', badge: false})` in Javascript) does not cause the notification dot on the homescreen app icon to be hidden, as described in the Android documentation.

Note that when the app is in the background or not running, no app code is executed since the Android OS handles the display of the system notification, so making any changes in `FirebasePluginMessagingService.java` will have no effect since `onMessageReceived()` is only called when the app is running in the foreground.

At this point, I have no suggestion as to how the notification dot can be hidden - `setShowBadge(false)` does not appear to work as described in the Android documentation.
Therefore I'm labelling this issue as a caveat of using the plugin, as opposed to a bug in the plugin code which can be fixed.
