### ISSUE TITLE
Question: Data received in the onMessageReceived callback on iOS devices

### ISSUE THREAD

**Issue by ivalex01** [dpa99c/cordova-plugin-firebasex#378]
Hello,

I'm sending notifications from the firebase api with custom data. The problem is as follows:
When I receive a notification in iOS and when I tap on it, in the onMessageReceived callback, the object with the notification data is not complete, only the title and message of the notification can be accessed, as well as the properties of the tap. Is there any way to access the other data of the notification when I tap on it, either in foreground or background?

I'm using the ios_data_notification message structure from the test project published in this repository, and using version 9.0.1-cli

Thanks.

**Comment by dpa99c** [comment]
When a notification message is received, all the available data fields that are received by the plugin are forwarded on to `onMessageReceived`. i.e. many of those in the `notification` object do not get delivered to the application by iOS. So if you want these fields to be available to your application in `onMessageReceived()` you should duplicate them into the `data` section of the message since this is guaranteed to be received in `onMessageReceived()`.

**Comment by ivalex01** [comment]
Hello,

Sorry, I've duplicated the information in the `data` section of the message, but I still can't access all the information in the `onMessageReceived()` callback.

I'm using the Legacy FCM API and this is the structure of the notification I send:

```
 {
    "content_available": true,
    "to": "X", 
    "notification": {
          "title": "Title",
          "body": "Text", 
           "sound": "default" 
    },
   "priority": "high", 
   "data": { 
       "notification_foreground": true,
       "id_notification": "123", 
        "notification_android_priority": 1,
        "custom_field": "Test" 
   }
}

```
I've also tried the message structure you posted in the test project but still no result.  In fact the `content-available` section doesn't come up in either case. The notifications are even duplicated when they reach the devices.

This is what I get by debugging with xcode:

```
FirebasePlugin [native] LOG: didReceiveMessage: {
    "collapse_key" = "app.package.name";
    "custom_field" = "Test";
    from = 1012351482101;
    "id_notification" = 123;
    notification = {
        body = "Text";
        e = 1;
        sound = default;
        sound2 = default;
        title = "Title";
    };
    "notification_android_priority" = 1;
    "notification_body" = "Text";
    "notification_foreground" = true;
    "notification_title" = "Title";
}
```
And this is what I get in the callback when I tap the notification:

```
   aps = {
        alert = {
            body = "Text";
            title = "Title";
        };
    };
    messageType = data;
    "notification_foreground" = true;

```

Is there something I'm missing? Or is it necessary to migrate to the FCM API V1?

Thanks in advance for your help.

**Comment by dpa99c** [comment]
Think this must be because you're using the legacy API - see [this screencapture](https://www.youtube.com/watch?v=35feCmGYSR4) from my iPhone 7 receiving a test message in the example project app via the FCM v1 API and you can see all the message data is available.

You can confirm this for yourself by building and running the example project app and using its built-in FCM v1 API client to send test messages to your device.

**Comment by mvergarair** [comment]
@ivalex01 did you fix this? I am having the same problem.

**Comment by ivalex01** [comment]
@mvergarair, I solved it by doing a fork adding the fields that I needed to have in the callback.
