### ISSUE TITLE
Signing out not prompting for account selection google login

### ISSUE THREAD

**Issue by ajmal1719** [dpa99c/cordova-plugin-firebasex#382]
I am unable to sign out and select another google account. I have to clear app data to sign in with a different account

**Comment by dpa99c** [comment]
I'm going to guess that you're encountering this issue with the iOS platform, though this is a guess since you haven't filled out the issue template.
This issue was fixed by commit https://github.com/dpa99c/cordova-plugin-firebasex/commit/9cd0c08d00e8d9b1af86c06bf7c6f2d1ec3e7e00 in relation to #353 so please update to the latest version of the plugin and retest.

If you still encounter the problem please test using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and open a new issue fully completing the issue template.
