### ISSUE TITLE
Cannot receive push notification when app is updated in App Store

### ISSUE THREAD

**Issue by yze77** [dpa99c/cordova-plugin-firebasex#391]
I have migrated my app from cordova-plugin-firebase to cordova-plugin-firebasex.
Everything worked fine when running on device from Xcode.
Everything worked fine when testing the app in TestFlight.
But when the App was published in the app store, and I pressed "update" to update my old app that was installed on my iPhone (that used the old plugin), and then tried to send a push notification, it did NOT work.
But if I uninstalled the app, and downloaded the new version again, it WORKS!.

Seems like there is an issue when the app is updated via app store, from a version that used cordova-plugin-firebase to one that uses cordova-plugin-firebasex.

Does this make any sense to you developer guys?

**Comment by dpa99c** [comment]
This is either caused by an APNS certificate issue between old vs new version or incompatibility between the old vs new version of the Firebase SDK components. Either way, I don't think anything can be done at the code level from within this plugin to resolve this issue. Since this isn't a scenario I can reproduce, you'll need to investigate further yourself to determine the cause.
