### ISSUE TITLE
Archive takes to long to finish

### ISSUE THREAD

**Issue by MLuan** [dpa99c/cordova-plugin-firebasex#407]
Hi, this is not a issue a think, is more like a doubt. 
After install firebasex using ionic 3, the size of my platform ios ( after build), increase like too must, duplice the size and the archive now takes almost a hour to finish. This is a regular behavior using this plugin?

**Comment by dpa99c** [comment]
Build times are very much dependent on the power of your dev machine: my machine takes about 40 seconds to build the example project for this plugin using Xcode 11.5.

The long build time is because this plugin includes most of the various components of the Firebase SDK and each of those includes external dependencies and build tasks. The Firebase Auth and Firestore components seem to include a particularly large number hence why v9 of this plugin sees an increase in build times since it pulls in these new SDK components.

There is nothing that can be done to reduce the build time except to reduce the dependencies and build tasks by removing Firebase SDK components you don't use (as outlined in #291) but until such time as this plugin is broken down into modular components, if you choose to use it as is, you will either have to live with the build times or fork it and remove the components you don't use yourself.

**Comment by ealbinu** [comment]
My machine takes almost 30 minutes :(

**Comment by petergrau** [comment]
We are facing the same issue. With the update from `v7` to `v9-cli` the build times increased by ~10 minutes.
