### ISSUE TITLE
Indicate if subscribe/unsubscribe to topic failed

### ISSUE THREAD

**Issue by svenboogaarthotraco** [dpa99c/cordova-plugin-firebasex#422]
# Documentation issue
What happens when the methods do not work.
E.g. if subscribe fails how can one detect it, as the return type is void according to https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts#L55

**Comment by dpa99c** [comment]
These functions are directly inherited from [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase).

Looking at the source code, neither [Android](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/android/FirebasePlugin.java#L638) or [iOS](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/FirebasePlugin.m#L333) returns a result for subscribe/unsubscribe actions.

However, looking at the Firebase documentation, it looks like [`subscribeToTopic` on Android](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessaging#subscribeToTopic(java.lang.String)) returns a Task object which should indicate a success/failed state, and on iOS it should be possible to change from using [subscribeToTopic:](https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Classes/FIRMessaging#-subscribetotopic:) to [`subscribeToTopic:completion:`](https://firebase.google.com/docs/reference/ios/firebasemessaging/api/reference/Classes/FIRMessaging#/c:objc(cs)FIRMessaging(im)subscribeToTopic:completion:) which also indicates if an error occurred. 

The same should be possible for unsubscribe actions.

So rather than being a documentation issue, this is a legacy code issue in that it doesn't actually indicate whether there was an occur in subscribing/unsubscribing to a topic.

I'll change the issue to reflect this.

**Comment by svenboogaarthotraco** [comment]
@dpa99c Is there another way I can check if subscribe if succesffull, e.g. is it possible to get my subscribtions? If thats possible I can validate if the expected subscribe is succesfull. Is it correct there is a few minutes delay between subscribe and when you can actually receive the messages? When testing in an android emulator it takes a few minutes before I can actually send messages to a subscribed device. PS, is there a forum or something where I should ask question. I have the feeling i should not post it under issues.

**Comment by Hao-Axon** [comment]
@dpa99c I get "Task failed for unknown reason" error from .subscribe now. But seems like the subscribe is actually successful and the app can receive messages after the error.
