### ISSUE TITLE
Build error !! - Add FIRApp configure - IOS

### ISSUE THREAD

**Issue by bigleesan** [dpa99c/cordova-plugin-firebasex#447]
Hello.
Spent a lot of time to build my project for IOS.
and I saved GoogleService-Info.plist in folder ( Project -> Resources )
I cannot find any reason why this would happen. Here is the code:

2020-07-09 09:53:20.006416+1200 pushtest[11839:871372] 6.27.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add [FIRApp configure]; (FirebaseApp.configure() in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.

//=======================================================
// ios environment
//=======================================================
cordova-lib@9.0.1 with:
cordova-common@3.2.1
cordova-create@2.0.0
cordova-fetch@2.0.1
cordova-serve@3.0.0

Environment:
OS: darwin
Node: v12.16.1
npm: 6.13.4

iOS platform:
Xcode 11.5

Reply : 
================================================================
dpa99c commented 1 hour ago
As documented:
================================================================

Download your Firebase configuration files, GoogleService-Info.plist for iOS and google-services.json for android, and place them in the root folder of your cordova project.

i.e. place in the same directory as your config.xml and run cordova prepare ios so the plugin picks up GoogleService-Info.plist and deploys it to the Xcode project.

================================================================

Hi,
Thanks, But I have a same error.
and Fairbase/core 6.17 is no error on another PC.
Please check below image file. It is your test sample.

Thanks

![img1](https://user-images.githubusercontent.com/51064966/87008681-3d335780-c218-11ea-8e6a-9a1d99a39e23.GIF)

**Comment by dpa99c** [comment]
OK I will see if I can replicate the issue and have a look at why this log message is being generated.

**Comment by dpa99c** [comment]
As far as I can see from [this SO post](https://stackoverflow.com/q/59245434/777265), this could arise from calling Firebase APIs before the FirebaseApp is configured.
However, I've checked the plugin source code and this is not happening since `[FIRApp configureWithOptions:options]` [is called](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/AppDelegate%2BFirebasePlugin.m#L71) right at the start of the [swizzled `didFinishLaunchingWithOptions`](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/src/ios/AppDelegate%2BFirebasePlugin.m#L53).

There is no definitive definition of the log message but it appears to be a warning not an error and I see no adverse effects on the functionality this plugin provides - unless you have encountered some?

Since this plugin includes many of the Firebase SDK components, it could be that one of those is internally calling a Firebase API before the FirebaseApp is configured.

So unless this log message is actually causing you an issue at runtime, I propose closing this issue on the basis that the log message is anomalous.

**Comment by dpa99c** [comment]
Closed due to no response

**Comment by kieranbehn** [comment]
I am also having the same issue on iOS. It seems one adverse affect is I am unable to receive Cloud Messaging notifications sent both to specific topics and specific FCM registration tokens.

I can also recreate this in your test project. Are notifications working for you with this warning message?

**Comment by dpa99c** [comment]
@kieranbehn yes notifications are working fine in both the test project and in my production apps which use this plugin.
Check your APNS configuration in Firebase is correct.
I believe this log message to be anomalous and therefore unrelated to your lack of notifications.

**Comment by kieranbehn** [comment]
Turns out my APNs configuration was the problem area! Issue resolved now thanks so much.
