### ISSUE TITLE
Custom Sound not working when notification arrive always default ringtone 

### ISSUE THREAD

**Issue by renznamoc21** [dpa99c/cordova-plugin-firebasex#448]
Custom Sound not working when notification arrive always default ringtone

**Comment by dpa99c** [comment]
Since you failed to complete the issue template it's hard to guess the exact scenario you're referring to but going by [your comment here](https://github.com/dpa99c/cordova-plugin-firebasex/issues/345#issuecomment-656862875) it seems you are having problems playing a custom sound on Android 10.

[As documented](https://github.com/dpa99c/cordova-plugin-firebasex#android-80-and-above), on Android 8+ it is the notification channel, not the FCM message payload, that defines which sound is played.

Please build and run the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and send the [android_notification_custom_channel](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/android_notification_custom_channel.json) test message using the built-in FCM client to confirm this.
You can also change the channel of one of the other test messages to confirm this: `android.notification.channel_id="my_channel_id"`

I have regression tested the lastest plugin version using the example project on a Pixel 2 running Android 10 and I'm satisfied the custom sound is being played as expected.

So if you are able to reproduce a scenario where this does not work within the example project, please open a new issue, completing the issue template to give full details such as the name of the test message which was sent and the device on which is was tested.
