### ISSUE TITLE
[FEATURE] Rich content in notifications

### ISSUE THREAD

**Issue by heidji** [dpa99c/cordova-plugin-firebasex#45]
title says it all.. can we have pictures in the notifications?

**Comment by dpa99c** [comment]
It seems [from this blog post](https://medium.com/@mail2ashislaha/rich-push-notification-with-firebase-cloud-messaging-fcm-and-pusher-in-ios-platform-8b4e9922120) that this is possible for iOS notifications, but not trivial (requires a "notification service extension").

For Android, it seems that rich notification content is not directly supported by FCM or by Android in its system notifications (displayed when app receives a notification message while app is in background/not running). However, it may be feasible to construct a foreground (local) notification using an FCM notification/data message and augment this to display the rich content.

So I'll adjust the title of this for the benefit of both platforms.

**Comment by heidji** [comment]
i did try some of these blog posts without luck and suspected that it might have something to do that the plugin already handles the notification (?)
please advise on how to proceed. I'm only talking about iOS here.

**Comment by heidji** [comment]
actually was able to implement it using [this guide ](https://pushwoosh.gitbook.io/platform-docs/pushwoosh-sdk/ios-push-notifications/ios-rich-notifications-integration).
Are you sure there is no way to do it with the plugin ? :D

**Comment by heidji** [comment]
there is also a fun issue: after adding a "new target" to an ionic generated xcode project any subsequent build by cordova fails with:
` Error during processing of action! Attempting to revert...
        Could not parse app.xcodeproj/project.pbxproj: Could not find 
        *-Info.plist file, or config.xml file.`

**Comment by dpa99c** [comment]
For anyone else seeing this:

Android: it's not (currently) possible to display pictures within system notifications

iOS: I don't believe there's an automated solution that this plugin could provide in order to display pictures within system notifications on iOS.
The reason being that it requires creating a Notification Service Extension in Xcode with its own separate Apple App ID and Provisioning profile. This does not work well in a Cordova project where the Xcode project is volatile.
Anyone wishing to attempt this will need to do some manually by following a guide such as [this](https://pushwoosh.gitbook.io/platform-docs/pushwoosh-sdk/ios-push-notifications/ios-rich-notifications-integration) as @heidji did.
So I'm closing this as it's not something this plugin can help with.

**Comment by heidji** [comment]
thanks for the explanation. i really did hope I wouldn't have to create a new extension in xCode each time i run a new build
