### ISSUE TITLE
[FEATURE] Grouping notifications

### ISSUE THREAD

**Issue by vkyeswa** [dpa99c/cordova-plugin-firebasex#46]
Inquiring if the plugin has the notification grouping feature as described in [the documentation](https://developer.android.com/training/notify-user/group.html)

**Comment by dpa99c** [comment]
The plugin doesn't current support this feature.

While it could be implemented for foreground notification messages / data notification messages (since this plugin code is responsible for building those notifications) I'm not sure if this could be achieved for system notifications (notification messages that arrive while app in background/not running) since this display of those notifications is entirely handled by the operating system (i.e. no plugin code is executed).

**Comment by vkyeswa** [comment]
after some reading i have managed to stack the notification by adding this to the notification bag from the server `notification : {..., style: "inbox", }` for Android

**Comment by dpa99c** [comment]
does that work for background and foreground notifications? - I presume just for background (system) notifications?

**Comment by etorresys** [comment]
@vkyeswa its not working for firebase REST V1, there's no attribute style. [Firebase Doc](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages)

**Comment by Amaury-T** [comment]
hello @vkyeswa, can you explain how you achieved stacking the notifications ?
as @etorresys said, it seems it is not present on the REST API...
