### ISSUE TITLE
iOS foreground notification always calls onMessageReceived

### ISSUE THREAD

**Issue by yoldar** [dpa99c/cordova-plugin-firebasex#48]
Hi! First of all thank you man for that great plugin! Take a donate for a cup of beer :)

Is that possible for foreground notification on iOS behave the same as on Android? I mean when app on iOS is foreground and push comes with notification_foreground=true just to show notification and if user taps it only then call onMessageReceived?

Because now when iOS is foreground there is no notification appears and onMessageReceived called. But it would be great to call onMessageReceived only when user taps notification in background(that works) and foreground modes.

**Comment by dpa99c** [comment]
I think it best that a notification message is always passed to `onMessageReceived()`, regardless if `notification_foreground: true` to ensure that, if the notification message contains an additional data payload, the app always receives it. So I think I will change Android to behave the same as iOS - on receiving a notification message in the foreground, always pass the message to `onMessageReceived()`.

However, I see that this could end up with `onMessageReceived()` being called twice if `notification_foreground: true`: once when the message arrives and once again if the user taps the foreground notification dialog. 
So I propose that the value of `tap` is used to distinguish this and leave it up to the app logic to determine how to handle to the calls to `onMessageReceived()`:
- notification message arrives while app is in foreground: `tap` is not set since user did not tap notification message
- notification message arrives while app is in background and user taps notification: `tap: "background"`
- notification message arrives while app is in foreground with `notification_foreground: true` and user taps foreground notification: `tap: "foreground"`.

This would be implemented on both platforms to allow managing all scenarios coherently cross-platform.

**Comment by dpa99c** [comment]
This has been rationalised in v6.0.0 which has been published to npm

**Comment by yoldar** [comment]
> This has been rationalised in v6.0.0 which has been published to npm

@dpa99c I have updated plugin and unfortunately on iOS on foreground mode there is no system push notification. Only onMessageReceived method called.

**Comment by dpa99c** [comment]
See [this screencapture](http://ge.tt/58jzEBx2) of a notification message being received in the foreground and displayed as a system notification on iOS.

This is using the [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test) to sent the [`notification.json` message](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/notification.json).

Please clone and building the example project, customise as necessary (i.e. change the app package ID to one under your control) and send the same message to confirm.
