### ISSUE TITLE
Android Studio Emulator - FirebasePlugin is not defined

### ISSUE THREAD

**Issue by franknoel** [dpa99c/cordova-plugin-firebasex#480]
As supposed, I'm able to receive use the library on any physical devices. 
However, when I try to test it on an emulator, I end up with the following error:
`Uncaught ReferenceError: FirebasePlugin is not defined`

Does this library support push notifications on any emulator? It is not clear in the documentation if it does.
In Android Studio, I am using the Android 9.0 (Google APIs) x86_64 target.

I also remember reading that some Android Studio image does support it.
https://stackoverflow.com/questions/20521600/android-emulator-not-receiving-push-notifications

**Comment by tsimbalar** [comment]
I believe I've seen this error in the past. For me it happened because something went wrong while installing the plugin.

Typically, when running `ionic cordova platform add ios` , it started installing the `firebasex` plugin, but it failed because of issues with cocoapods. The build carried on though, and the app was opening in the emulator, but was failing at runtime.

Do you maybe have the same issue ?

**Comment by dpa99c** [comment]
It works fine in the Android Emulator. Something is wrong with your build so the plugin is not installed.
Please use the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) to validate your build environment.
