### ISSUE TITLE
Add enableForegroundNotifications() to documentation

### ISSUE THREAD

**Issue by besserwisser** [dpa99c/cordova-plugin-firebasex#49]
First of all: Thank you so much for this plugin, it helped a lot!

The README file does not mention the FirebasePlugin.enableForegroundNotifications() function. I have been trying to get the foreground notifications working on iOS for hours now until I found [https://github.com/dpa99c/cordova-plugin-firebasex/issues/10](this) issue mentioning the enableForegroundNotifications function. After using it, the foreground notifications work (of course when using the data->notification_foreground attribute in the JSON). It would have helped a lot, if this necessary function call would be mentioned in the README. 

Thanks

**Comment by dpa99c** [comment]
Issue #10 references PRs against [cordova-plugin-firebase](https://github.com/arnesson/cordova-plugin-firebase) that would-be-nice to merge into this fork of the plugin.

Among them, [Added API method enableForegroundNotifications()](https://github.com/arnesson/cordova-plugin-firebase/pull/1056) is a PR which disables foreground notifications by default and enables them via that function.

However that PR **has not been merged into this plugin fork** so `enableForegroundNotifications()` does not exist in `cordova-plugin-firebasex`. 
That PR is unnecessary for this fork since display of foreground notifications can now be controlled entirely remotely using the `notification_foreground` key in the data message payload, hence I will remove it from #10.
