### ISSUE TITLE
User not created in Firebase Console after Apple Authentication

### ISSUE THREAD

**Issue by codexsysin** [dpa99c/cordova-plugin-firebasex#505]
# Bug report

**CHECKLIST**
- [x] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [x] I confirm this is a suspected bug or issue that will affect other users

- [x] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [x] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [x] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

It throws an error " no native auth credential exists for specified id '75391' "
![image](https://user-images.githubusercontent.com/12164671/92435179-4ceefe00-f1bf-11ea-982b-fbedf8145721.png)

**Expected behavior:**

SigninWithCredential must post an OK response after passing credentials into it. But throws the following error

**Screenshots**
![image](https://user-images.githubusercontent.com/12164671/92435493-14035900-f1c0-11ea-91a6-26d8cd18b2b7.png)

**Environment information**

- Cordova CLI version 
	- 9.0.0 (cordova-lib@9.0.1)
- Cordova platform version
	- Installed platforms:
  android 8.1.0
  ios 5.1.1
- Plugins & versions installed in project (including this plugin)
    - cordova-plugin-androidx 2.0.0 "cordova-plugin-androidx"
cordova-plugin-androidx-adapter 1.1.1 "cordova-plugin-androidx-adapter"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-enable-multidex 0.2.0 "Enable Multidex"
cordova-plugin-firebasex 10.2.0-cli "Google Firebase Plugin"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 5.0.4 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-sqlite-storage 5.0.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"

- Dev machine OS and version, e.g.
    - OSX
        - ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G6020
        
_Runtime issue_
- Device details
    -   iPhone X Simulator, iPhone 6s
- OS details
    - iOS 13.3	
	

**Related code:**

![image](https://user-images.githubusercontent.com/12164671/92435432-ea4a3200-f1bf-11ea-9b5f-ed33747f5da8.png)

**Comment by codexsysin** [comment]
@dpa99c Hi, can you help on this?

**Comment by dpa99c** [comment]
I'm unable to reproduce this issue either in the example project (or my own production apps which make use of this functionality):


After pressing "Authenticate with Apple", `autheticateUserWithApple()` is called:
![1](https://user-images.githubusercontent.com/2345062/93209011-5d6e1e00-f755-11ea-9c85-a6285a841491.png)

On providing the requested authentication, the plugin receives the `FIROAuthCredential` object which it stores in a lookup and returns the corresponding key (`89703`) back as the plugin result:
![2](https://user-images.githubusercontent.com/2345062/93209020-6101a500-f755-11ea-89f8-aad833052715.png)


The example app then stores a reference to this credential result: 
![3](https://user-images.githubusercontent.com/2345062/93209023-6232d200-f755-11ea-9920-4e34bedd4750.png)

Which is referenced when calling `signInWithCredential()`:
![4](https://user-images.githubusercontent.com/2345062/93209025-62cb6880-f755-11ea-97ea-9a593bf86248.png)

The native implementation of this obtains the native `FIRAuthCredential` by looking up the credential result passed in as an argument:
![5](https://user-images.githubusercontent.com/2345062/93209027-63fc9580-f755-11ea-9fe8-ace075512eef.png)

This is done by looking up the "id" key specified in the JSON object:
![6](https://user-images.githubusercontent.com/2345062/93209030-64952c00-f755-11ea-9ca8-4d921bc0725d.png)

The returned native credential is the used to make a sign-in request:
![7](https://user-images.githubusercontent.com/2345062/93209034-652dc280-f755-11ea-8fea-257df5a0118a.png)

The result of which is successful:
![8](https://user-images.githubusercontent.com/2345062/93209036-665eef80-f755-11ea-9eb8-8b1584ef36c2.png)

So the example app's success callback handler is invoked:
![9](https://user-images.githubusercontent.com/2345062/93209040-66f78600-f755-11ea-9278-bc48d506aff9.png)


I also tried making the sign-in call immediately upon receiving the Apple credential (as you have in your code snippet) in case there was a race condition in storing the credential object but I couldn't repro the issue this way either:
![10](https://user-images.githubusercontent.com/2345062/93210202-17b25500-f757-11ea-9cb5-1106ad2f4b70.png)

Please try to replicate this issue use the example project since it's a known reference codebase.

**Comment by codexsysin** [comment]
Hi Dave,

Thank you for your reply.
Example project is working fine in the Xcode.

**Without WKWebView**
![image](https://user-images.githubusercontent.com/12164671/93270864-9519ac00-f7cf-11ea-8b83-751b38773988.png)

**With WKWebView**
![image](https://user-images.githubusercontent.com/12164671/93270717-508e1080-f7cf-11ea-9a06-29399a8930f5.png)

Since the example project doesn't use the WKWebView. It's working fine. 

Any resolution for WKWebView, @dpa99c ? Can you able to check whether you can reproduce the same issue?

**Comment by dpa99c** [comment]
> Since the example project doesn't use the WKWebView. It's working fine.

The example project [is configured](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/package.json#L41) to use the latest `cordova-ios@6.1.1` platform release.

`cordova-ios@6` was a [major release](https://github.com/apache/cordova-ios/blob/master/RELEASENOTES.md#600-may-28-2020) which replaces UIWebView with WKWebView:
> [GH-773](https://github.com/apache/cordova-ios/pull/773) refactor: drop uiwebview & add wkwebview

So the example project *is* using WKWebView.

You can confirm this by running the following feature detection command in the JS console of Web Inspector:

    (window.webkit && window.webkit.messageHandlers ? "wkwebview" : "uiwebview")

Have you added some additional 3rd party plugin to the example project such as [cordova-plugin-wkwebview-engine](https://github.com/apache/cordova-plugin-wkwebview-engine) or [cordova-plugin-ionic-webview](https://github.com/ionic-team/cordova-plugin-ionic-webview)?

**Comment by codexsysin** [comment]
We have added cordova-plugin-ionic-webview in our project.

**Comment by codexsysin** [comment]
Hi Dave,

Found that the working version of example project uses UIWebView not WKWebView so please check whether the issue is with WKWebView.

![image](https://user-images.githubusercontent.com/12164671/93322148-a050f400-f830-11ea-9a71-cbbcf4897a81.png)

and this is the package.json of firebasex example project 

![image](https://user-images.githubusercontent.com/12164671/93322614-240ae080-f831-11ea-97fd-64cf2a25c6f6.png)

**Comment by dpa99c** [comment]
The `package.json` in your screenshot is not the same as the [`package.json` on the master branch](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/package.json#L41) of the example project, which pins `cordova-ios@6.1.1` - please try `git pull && git reset --hard origin/master` in your local checkout of `cordova-plugin-firebasex-test` to ensure you have the latest version.

Or do `cordova platform rm ios && cordova platform add ios@latest`

**Comment by dpa99c** [comment]
> We have added cordova-plugin-ionic-webview in our project.

I've tried the example project with `cordova-plugin-ionic-webview@5.0.0` and Sign in With Apple worked fine

**Comment by codexsysin** [comment]
We're trying to create a new project and import the existing code to new. Thanks for your efforts, Dave. We'll check and update in couple of days. Nice day.

**Comment by dpa99c** [comment]
Closed due to no response
