### ISSUE TITLE
Export types

### ISSUE THREAD

**Issue by loopezz** [dpa99c/cordova-plugin-firebasex#529]
# Feature request

Export types for type hinting for better TypeScript support. Exporting these interfaces should be nice:
[https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts)

**Comment by dpa99c** [comment]
Do you mean literally prefixing each `interface` with `export`, i.e. `export interface Foo` ?

**Comment by kamilbrk** [comment]
I'm afraid that this broke existing integrations and it's inconsistent with other Cordova plugins


Without `export` statements:

![Screenshot 2020-10-27 at 13 09 44](https://user-images.githubusercontent.com/591349/97306477-72f75d00-1856-11eb-9cd4-f441d448bfc4.png)

With `export` statements (since 5e349af):

![Screenshot 2020-10-27 at 13 10 18](https://user-images.githubusercontent.com/591349/97306486-75f24d80-1856-11eb-8a51-c231457b0186.png)

**Comment by loopezz** [comment]
I have made a wrapper service for better integration with **Angular** and **TypeScript**. I converted almost all functions to real promises:
![Screenshot 2020-10-27 at 15 23 52](https://user-images.githubusercontent.com/11312418/97315158-b6f35d80-1868-11eb-9fbf-db8c1fc07f99.png)

To get this type safety I have added FirebasePlugin to my typings.d.ts:
![Screenshot 2020-10-27 at 15 24 25](https://user-images.githubusercontent.com/11312418/97315398-f8840880-1868-11eb-8a38-4ac5456708d4.png)

--------
However, your issue is about how [these interfaces](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts) are declared. You should pass the required arguments for [getToken()](https://github.com/dpa99c/cordova-plugin-firebasex/blob/master/types/index.d.ts#L19). If you don't have any callbacks for getToken(), then just do the following:
```
window.FirebasePlugin.getToken(() => {}, () => {});
```

**Comment by kamilbrk** [comment]
> However, your issue is about how these interfaces are declared. You should pass the required arguments for getToken(). If you don't have any callbacks for getToken(), then just do the following:
> ```ts
> window.FirebasePlugin.getToken(() => {}, () => {});
> ```

Apologies, maybe that was not too clear.

The first screenshot meant that I can get type definitions and it actually tells me that I need callbacks for `getToken()`, meaning that typings were loaded correctly. I realise that they need to be supplied, it was to demonstrate the point of IDE detecting missing arguments (callbacks).

The second screenshot meant that it couldn't detect any typings whatsoever, so it highlighted `FirebasePlugin` as unknown. This is something that does not happen for other (core) plugins from my experience, _perhaps because of adding `export` statements_.

> To get this type safety I have added FirebasePlugin to my typings.d.ts:
> ```ts
> interface Window {
>   FirebasePlugin: import('../cordova/node_modules/cordova-plugin-firebasex').FirebasePlugin;
> }
> ```

The fact that you had to add this code to your own `typings.d.ts` probably demonstrates the reason why other Cordova plugins (mostly core/under Apache org) do [that same thing in their own definitions](https://github.com/apache/cordova-plugin-statusbar/blob/master/types/index.d.ts#L10-L11). My understanding is that adding:

```ts
interface Window {
  FirebasePlugin: FirebasePlugin;
}
```

…would mean that you wouldn't have to do this `import` by yourself. At least that's the behaviour I can observe with other plugins.

Could you share a thought on how do you work with other plugins, perhaps official/core plugins from Apache org on GitHub? Do you also `import` them into your project? Do they work out of the box without `import`ing?

**Comment by peitschie** [comment]
We've hit this one as well.

It turns that putting the `export` on the interfaces makes TypeScript decide this is a Module now rather than a Namespace: https://www.typescriptlang.org/docs/handbook/modules.html

> In TypeScript, just as in ECMAScript 2015, any file containing a top-level import or export is considered a module. Conversely, a file without any top-level import or export declarations is treated as a script whose contents are available in the global scope (and therefore to modules as well).

The easiest way to fix is this move the declare var within a global scope like this:
```
declare global {
    const FirebasePlugin: FirebasePlugin;
}
```
