### ISSUE TITLE
Query on Push tracking

### ISSUE THREAD

**Issue by StephenMok1997** [dpa99c/cordova-plugin-firebasex#531]
Is there any method for identifying the following actions for notification message and data message? If not, it is possible to add this feature to the plugin?

Push Tracking is separated into three types:
- Push Impressions - When a push notification has been delivered to the device and is sitting on the notification center but hasn't been touched at all. This is considered an impression. In most cases impressions numbers should be similar if not the same as the delivered number. It ensures that the device did get the message and relayed that information back to the server.

- Push Click - When a push notification has been delivered to the device and the user has clicked on the device. The user either wanted to view the notification (which will in turn move to Push Open tracking) or dismiss the notification.

- Push Open - When a push notification has been delivered to the device and the user has clicked on the notification causing the app to open. This is similar to the Push Click except a Push Open will not be triggered if the notification was dismissed.`

**Comment by dpa99c** [comment]
> Is there any method for identifying the following actions for notification message and data message? 

Data messages are not intended to be user-facing therefore the following applies only to notification messages:

> * Push Impressions - When a push notification has been delivered to the device and is sitting on the notification center but hasn't been touched at all. This is considered an impression. In most cases impressions numbers should be similar if not the same as the delivered number. It ensures that the device did get the message and relayed that information back to the server.

When a notification message arrives while the app is in the foreground, it will be immediately delivered and the [`onMessageReceived()`](https://github.com/dpa99c/cordova-plugin-firebasex#onmessagereceived) callback will be invoked.
The `tap` property will not be present, indicating the app received with message without user interaction (i.e. it's an impression).

When a notification message arrives while the app is in the background/not running, no plugin code is invoked until the app is next launched (either when the user taps a system notification or launches the app manually). At app startup, the plugin will loop over any pending notification messages and deliver them to the app via the `onMessageReceived()` callback. Again, an impression is denoted by the lack of a `tap` property indicating no user interaction caused delivery of the message.

> * Push Click - When a push notification has been delivered to the device and the user has clicked on the device. The user either wanted to view the notification (which will in turn move to Push Open tracking) or dismiss the notification.

Since no plugin code is executed when the user interacts with a system notification unless they tap on it (triggering a "Push Open") it is not possible to track this.

> * Push Open - When a push notification has been delivered to the device and the user has clicked on the notification causing the app to open. This is similar to the Push Click except a Push Open will not be triggered if the notification was dismissed.`

When the user taps a notification, the `onMessageReceived()` callback will be invoked and the `tap` property will be present on the notification object. If the user tapped a system notification, `tap: "background"` will be set; if the user tapped a foreground notification `tap: "foreground"` will be set.

I hope this answers your question.
