### ISSUE TITLE
cordova-plugin-firebasex@x.x.x-cli should be published as its own plugin (cordova-plugin-firebasex-cli)

### ISSUE THREAD

**Issue by jpike88** [dpa99c/cordova-plugin-firebasex#559]
When I use node update checker (ncu), it always thinks that cordova-plugin-firebasex@11.0.3-cli is behind cordova-plugin-firebasex@11.0.3, and this probably because it doesn't follow the rules of semver.

I think it's ideal to release the cli variant as its own plugin name, which allows semver to be followed strictly and not break other tools.

Thanks for the great work

**Comment by dpa99c** [comment]
I don't plan to create a new repo/plugin as it would be an additional overhead to maintain 2 versions of the same codebase, particularly since the CLI version of the plugin only exists to workaround a bug in the Cordova iOS platform which hopefully will be fixed sometime soon.
However, you are welcome to create/publish/maintain a new plugin based on the latest-cli tag in this plugin.

**Comment by jpike88** [comment]
@dpa99c I don't see how you'd need a new repo? Why not write a quick little script that modifies the package.json name and  publishes it? Ugly but better?

We just ran into an issue where our package got 'downgraded' from the cli branch again...
