### ISSUE TITLE
Is it possible to be more specific with JavaScriptExceptions in Crashlytics?

### ISSUE THREAD

**Issue by zaitsev1393** [dpa99c/cordova-plugin-firebasex#583]
Hi!

So the simple question is if it is possible to separate JS exceptions under the line where plugin throws exception like that:

**FirebasePlugin.java - line 704**

Into something more specific? Because all JS errors are grouped under this one and it is hard to read them and also impossible to understand how much that or this issue affected the app. So the expected behaviour is something like
this:

**TypeError: undefined is not an object**

etc... 

Thanks for response in advance!

**Comment by Didji** [comment]
From what I understood, this happens when you leave the stackTrace parameter to null. The plugin will then generate a stack trace from the point where it sends the error, resulting in this behaviour.

That said, using stacktrace.js to generate a generic stacktrace like so :
```js
StackTrace.get().then(function (stackframes) {
    Logger.triggerLogging(rejection, stackframes);
});
```
Doesn't help either, because all your messages end up in the same category of `stacktrace.min.js line 1`

The "problem" lies more with the Crashlytics console that groups errors based on the last line of their stracktrace.

I'm currently trying to manually throw errors everywhere I need the errors to be logged and use the window.onerror handler listed in [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#logerror) to catch them. 

The idea is that the `StackTrace.fromError(error)` function will generate different stacktraces based on the error I threw, which will then be properly separated in the web interface.

**Comment by Kosmonaft** [comment]
I'm getting the following error `Cannot find name 'StackTrace'`
