### ISSUE TITLE
Build fails with Compiler Clang error

### ISSUE THREAD

**Issue by cloudexpresssolutions** [dpa99c/cordova-plugin-firebasex#594]
# Bug report

**CHECKLIST**
- [ Yes] I have read the [issue reporting guidelines](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-issues)

- [ yes] I confirm this is a suspected bug or issue that will affect other users

- [ yes] I have reproduced the issue using the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) or provided the necessary information to reproduce the issue.

- [ yes] I have read [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex) thoroughly and it does not help solve my issue.

- [ yes] I have checked that no similar issues (open or closed) already exist.

**Current behavior:**

I installed the firebasex plugin and my build fails with the following error.

** BUILD FAILED **

The following build commands failed:
	CompileC /Users/cloud/Library/Developer/Xcode/DerivedData/forevaCorp-aeeboxoidohmizaelqtdywizxlth/Build/Intermediates.noindex/forevaCorp.build/Release-iphonesimulator/forevaCorp.build/Objects-normal/x86_64/FirebasePlugin.o /Users/cloud/Downloads/Megam/Builds/forevaCorp/platforms/ios/forevaCorp/Plugins/cordova-plugin-firebasex/FirebasePlugin.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65

**Expected behavior:**
 - I expect the build to succeed.

**Steps to reproduce:**
 ionic Cordova build iOS --release

**Screenshots**

**Environment information**

Ionic:

   Ionic CLI          : 5.4.16
   Ionic Framework    : ionic-angular 3.9.9
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 10.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.2.1, (and 25 other plugins)

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v10.16.3 (/usr/local/bin/node)
   npm        : 7.5.3
   OS         : macOS Big Sur
   Xcode      : Xcode 12.3 Build version 12C33
        
_Runtime issue_
- Device details
    - NA
- OS details
    - Mac BigSur

**Comment by akramn** [comment]
Hi there,
It seems that you have installed the default package which doesn't support cli builds for ios.
To fix that problem you need to use the cli package instead [**as stated in the documentation**](https://github.com/dpa99c/cordova-plugin-firebasex#cordova-cli-builds)
 simply run:
`ionic cordova plugin rm cordova-plugin-firebasex && cordova plugin add cordova-plugin-firebasex@latest-cli`
this should fix your problem 😉  but you won't be able to use Firebase Inapp Messaging and Google Tag Manager SDK in your project (which mostly you won't need)
But if you need to use them you can use the default package and build it using **xcode** ONLY(cordova will throw an error, you need to complete your build using xcode by opening **.xcworkspace** file instead of .xcodeproj)

PS: it seems that you haven't installed cordova-res and native-run, you can install them by running this commands:
`sudo npm i -g native-run `
`sudo  npm i -g cordova-res `

when building your app for production use use this command instead:
`ionic cordova build ios --aot --prod --release` 
otherwise your app going to be slow and feels less native

**Comment by janarieldev** [comment]
I am also having the exact same issues. I tried the suggestion of @akramn but unfortunately it didn't work.

**Comment by akramn** [comment]
@janarieldev can you provide more details so that I can help you?
your build error, package.json and config.xml

**Comment by janarieldev** [comment]
Sure thing! @akramn 

**Build Error:**

```
** BUILD FAILED **
The following build commands failed:
	CompileC /Users/jans/Library/Developer/Xcode/DerivedData/Jan_Demo-ezzudrdjxjuryrelorjwgnnrbpib/Build/Intermediates.noindex/Jan\ Demo.build/Release-iphonesimulator/Jan\ Demo.build/Objects-normal/arm64/AppDelegate+FirebasePlugin.o Jan\ Demo/Plugins/cordova-plugin-firebasex/AppDelegate+FirebasePlugin.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65
[ERROR] An error occurred while running subprocess cordova.
```

**Comment by akramn** [comment]
@janarieldev yes I need them both without cutting anything

**Comment by dpa99c** [comment]
There is sufficient detail in the error log to diagnose the problem.
Please see the [Reporting a bug or problem](https://github.com/dpa99c/cordova-plugin-firebasex#reporting-a-bug-or-problem) section, specifically with regard to using the `--verbose` CLI build flag to generate a full build log containing details of the error then open a new issue containing the verbose log if necessary.
Please also see the various [iOS-specific](https://github.com/dpa99c/cordova-plugin-firebasex#ios-specific) notes as they contain solutions for the most common causes of build failures.
