### ISSUE TITLE
Question: handling data message while app is not running

### ISSUE THREAD

**Issue by Dewep** [dpa99c/cordova-plugin-firebasex#67]
Hello,

Until yesterday, I was using the version of https://github.com/arnesson/cordova-plugin-firebase, which I had modified a little for personal needs.
My main need is to be able to delete notifications automatically, following the receipt of a notification with data only.

To make it very simple and so that you understand my need, let's say that I have a messaging application (like Slack, Messenger,...). The user receives the messages by notifications, which I "regroup" by conversation using the `notification.tag` available on Android (the next notifications will also contain the other unread messages of the conversation, the tag being the conversation ID). But when the user reads the conversation from another device, I want to delete the notification from the same tag.

On my fork, I simply edited the `FirebasePluginMessagingService.onMessageReceived` method, and in the case there is a `removeTag` key in the `data` payload, I run `notificationManager.cancel(remoteMessage.getData().get("removeTag"), 0);`. This workaround does not seem to be possible in your version, since these handling methods are never called when the application is not running.

Is it possible to have a similar behavior on your version? Even from the `FirebasePlugin.java` file, I can't add a handler that is called when the app doesn't run in background.

Thanks.

**Comment by dpa99c** [comment]
The mechanism used by `cordova-plugin-firebasex` to receive incoming FCM messages via the `FirebasePluginMessagingService` has not been changed since when it was forked from `cordova-plugin-firebase` (you can confirm this by [diffing the two plugins](https://github.com/arnesson/cordova-plugin-firebase/compare/master...dpa99c:master?expand=1)).

Therefore there's no difference in the way in which the `onMessageReceived` override (delegate) method is invoked by the core Firebase service on the device when a notification message is received.

As outlined in [the Firebase documentation](https://firebase.google.com/docs/cloud-messaging/android/receive):

> Firebase notifications behave differently depending on the foreground/background state of the receiving app. If you want foregrounded apps to receive notification messages or data messages, you’ll need to write code to handle the `onMessageReceived` callback.
> When your app is in the background, Android directs notification messages to the system tray. A user tap on the notification opens the app launcher by default.
>This includes messages that contain both notification and data payload (and all messages sent from the Notifications console). In these cases, the notification is delivered to the device's system tray, and the data payload is delivered in the extras of the intent of your launcher Activity.


Hence `onMessageReceived` is only invoked while the app is running in the foreground; if the app is not running when the notification message arrives, this is handled by the Android operating system as a system notification (i.e. no call is made to invoke app code) and upon a user tapping the system notification, only then will the app code be invoked and the notification message payload be passed to the app as an extras bundle on the intent of the app's Cordova Activity.

Therefore it's not possible for this plugin to achieve what you desire: for app code to be invoked in response to an FCM notification message arriving while the app is not running without the user tapping the system notification.

If you are in doubt of this, I suggest regression testing this exact scenario with `cordova-plugin-firebase` and I'm sure you will find that `onMessageReceived` is not invoked if the app is not running (vs running but backgrounded).

**Comment by Dewep** [comment]
> If you are in doubt of this, I suggest regression testing this exact scenario with `cordova-plugin-firebase` and I'm sure you will find that `onMessageReceived` is not invoked if the app is not running (vs running but backgrounded).

I have just tested again, in the version I have of the plugin, my Java code is called, even if the application is not running (neither in foreground, nor in background). But I'm actually using an old version of the plugin: https://github.com/arnesson/cordova-plugin-firebase/tree/ff9232350761ee3550bb9f6a4f4bcc1930f10e54 (https://github.com/arnesson/cordova-plugin-firebase/compare/ff9232350761ee3550bb9f6a4f4bcc1930f10e54...dpa99c:master?expand=1).

Too many changes to compare, but what is certain is that it was possible, and that I couldn't update the plugin because it prevented me from still being able to do that.

This kind of behavior works with other applications too (Messenger messages, Gmail emails that disappear once read from another device, etc.). So I doubt that there is no way to do the same thing with Firebase, right?

But since I don't know much about this field, I would have thought that you could at least have given me some guidance on how to proceed, I don't feel like I'm asking for some crazy functionality.

**Comment by dpa99c** [comment]
[The old version](https://github.com/arnesson/cordova-plugin-firebase/tree/ff9232350761ee3550bb9f6a4f4bcc1930f10e54) you have referenced uses exactly the same method for receiving FCM messages as this plugin.

AFAIK there is no way to have your app execute code on Android when an FCM push notification arrives and the app is not running.
[See this SO post](https://stackoverflow.com/questions/37358462/firebase-onmessagereceived-not-called-when-app-in-background) for some more discussion of this.

To acheive the functionality you desire - sending notification messages to multiple devices-per-user and when the user opens the notification on one, having the notifications cleared on the others - is quite a specific use case.
It's possible you may be able to achieve this by leveraging existing FCM functionality such as [device groups](https://firebase.google.com/docs/cloud-messaging/android/device-group) and [collapsible messages](https://firebase.google.com/docs/cloud-messaging/concept-options#collapsible_and_non-collapsible_messages) but this is beyond the scope of this plugin so if you require help with this, I'd advise you search/ask on stackoverflow for help with this.
