### ISSUE TITLE
Cli command not working with android 

### ISSUE THREAD

**Issue by Surinderkaur329** [dpa99c/cordova-plugin-firebasex#698]
Hi @dpa99c 

Below command working well for ios but for android its not working and build failed .
cordova plugin add cordova-plugin-firebasex@latest-cli

So i have just one query do we need to use different commands for ios and android  

for ios:             "cordova-plugin-firebasex": "13.0.0-cli",
for android :    "cordova-plugin-firebasex": "^13.0.0-cli"

Looking forward..

**Comment by dpa99c** [comment]
Not enough info. Please complete issue template in full if you want assistance.

**Comment by sebastian-zarzycki** [comment]
I might be of help here. I've updated firebase-x from 9.1.1-cli to 13.0.1-cli and the build now errors with:
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> groovy.lang.MissingMethodException: No signature of method: org.gradle.api.internal.model.DefaultObjectFactory.directoryProperty() is applicable for argument types: () values: []

BUILD FAILED in 0s
[ERROR] An error occurred while running subprocess cordova.
```

This is compiled using java 8 and cordova-android 8.1.0, as before. I suspect bumping one of them (or both) should help?

**Comment by storytellerr** [comment]
Facing same issue, on capacitor framework @sebastian-zarzycki did you find a workaround?


 `Caused by: groovy.lang.MissingMethodException: No signature of method: build_3sxz7cu5ies45305jksrqawcx.android() is applicable for argument types: (build_3sxz7cu5ies45305jksrqawcx$_run_closure2) values: [build_3sxz7cu5ies45305jksrqawcx$_run_closure2@4b4974ab]`

**Comment by JustDoItSascha** [comment]
Same issue here. Please reopen this issue.
