### ISSUE TITLE
Status on continued maintenance

### ISSUE THREAD

**Issue by jpike88** [dpa99c/cordova-plugin-firebasex#704]
@dpa99c do you intend to maintain this repo anymore? I'm blocked by a pretty severe bug which is preventing local development via simulator. #678

I have already forked and made fixes (but they are hacky and do the bare minimum to make it work, would need another few minutes of my time to prep them nicely for a PR).

**Comment by dpa99c** [comment]
I'm not using this plugin myself much any more but I'll see if I can find time to merge some PRs and address some of issues which are obviously bugs. 

That said, I have given up trying to investigate/respond to all issues across all my open-source repos as it's like trying to fight a forest fire with a water pistol:
My experience has been 90%+ of the issues opened are due to not reading the documentation or other user error and I have become sick of wasting my time due to other people's laziness.

My general approach now is I will only investigate an issue if it a) affects me or b) is raised by enough people for it to be obvious there's a general problem (as is the case with #678).

**Comment by jpike88** [comment]
maybe worth doing an issue culling! you may find your cognitive load is much lighter when you don't have so many issues in your face

**Comment by dpa99c** [comment]
> maybe worth doing an issue culling! you may find your cognitive load is much lighter when you don't have so many issues in your face

I took that approach initially to but to cull an issue involves investigating whether it's valid and to do that properly in itself takes a good deal of time.  Across all my open-source repos there are hundreds of open issues, most of which are invalid if investigated.
