### ISSUE TITLE
Clarify Capacitor Compatibility

### ISSUE THREAD

**Issue by wiverson** [dpa99c/cordova-plugin-firebasex#775]
# Documentation issue

Capacitor looks like it supports [most of Cordova](https://capacitorjs.com/docs/cordova/migrating-from-cordova-to-capacitor). It's unclear from the documentation if a) this plugin works with Capacitor and if so b) the best way to go about installing/using it.

If this plugin doesn't work with Capacitor, that should be noted. If it does, ideally there should be docs on how to use it.

If the intent is that this plugin should work with Capacitor but help is needed writing validating/writing docs, I might be able to help out with that.

**Comment by auflint** [comment]
+1 and if it is compatible, how to go about utilizing the variables at install.

**Comment by TiBz0u** [comment]
> +1 and if it is compatible, how to go about utilizing the variables at install.
I think it's not feasible without adapting the plugin. For Android, we need to go with a full gradle configuration for example. That will impact too Cordova users because they would need to use build-extras.gradle or gradle.properties instead of plugin variables.
@dpa99c what do you think?

Seems a ticket is still open regarding firebasex and other library at Capacitor https://github.com/ionic-team/capacitor/issues/3376.

**Comment by dpa99c** [comment]
Note added to the docs clarifying that Capacitor is not currently supported and why:
https://github.com/dpa99c/cordova-plugin-firebasex#capacitor-support
