### ISSUE TITLE
It takes time to build the app for iOS

### ISSUE THREAD

**Issue by El-Tommy** [dpa99c/cordova-plugin-firebasex#794]
When trying to run `cordova build ios` while installing the firebasex plugin I noticed that it takes more than 5 minutes to complete the build.
But if I remove the plugin the build takes less than 1 minute.

Is this behavior normal or could there be a problem with my machine?

**Comment by ndrake** [comment]
I'm seeing similar behavior with our app when upgrading to v16.0.0-cli.  I haven't attempted to reproduce with the cordova-plugin-firebasex-test project yet.  Our app using v14.2.1-cli, averaged an iOS build time of 1 minute 22 seconds. With v16.0.0-cli the average build time is 5 minutes 11 seconds.

If I get some time, I'll attempt to recreate with cordova-plugin-firebasex-test, but I'm not sure when I'll have time to do that.

**Comment by El-Tommy** [comment]
Would the v14.2.1-cli and v16.0.0-cli be your Node or NPM version?

**Comment by ndrake** [comment]
> Would the v14.2.1-cli and v16.0.0-cli be your Node or NPM version?

Those are the versions of this plugin that I'm using.

**Comment by El-Tommy** [comment]
I confirmed, my plugin version is also ^16.0.0.

**Comment by dpa99c** [comment]
The cause of longer build times on iOS when using v16+ of this plugin is because it now defaults to using the official (uncompiled) Firestore pod from the Firebase SDK, instead of the (unofficial) pre-compiled version (in v15 and below).
This is because of an issue with using the latest version of the pre-compiled pod in a Cordova build environment.
See https://github.com/dpa99c/cordova-plugin-firebasex/issues/782 and https://github.com/invertase/firestore-ios-sdk-frameworks/issues/62#issuecomment-1333449395

**Comment by El-Tommy** [comment]
Thanks for the answer.
I think with that it is possible to close this issue.

**Comment by roman-rr** [comment]
Such increasing in building time make the rapid developing is quite difficult.
What do you think @dpa99c, will firebase-sdk come back to pre-compiled version ?
Or maybe is good time to switch into capacitor development (I guess there is building time much faster than cordova) ?

**Comment by dpa99c** [comment]
@roman-rr The increased iOS build time is due to compiling the Firestore component of the Firebase SDK.
Cordova/Capacitor are only wrappers around the native Webview that enable a webapp to be deployed as a native app.
Therefore switching to Capacitor will not speed up the build.
