### ISSUE TITLE
Add actions on notifications for Android

### ISSUE THREAD

**Issue by rifatosmani** [dpa99c/cordova-plugin-firebasex#817]
Hi,
I need to add actions to my notifications when my app is closed. For now all i do with my notifications is the "tap" action, and i need to Confirm/Deny buttons without opening the app.
I noticed that this feature is available for iOS in the documentation. I was wondering if a similar feature could be added for Android as well.
Thanks

**Comment by dpa99c** [comment]
Firebase Cloud Messaging doesn't support action notifications ([see here](https://stackoverflow.com/a/64968885/777265)) so you'd need to send it as a data notification then use the payload to create a custom local notification with the action buttons, for example using [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications?tab=readme-ov-file#actions).

IMO this is beyond the scope of this plugin since there are many ways a local notification could be created, and too many options so this is best handled by the app developer for their specific case.
