### ISSUE TITLE
Notification Icon app crash at start

### ISSUE THREAD

**Issue by globules-io** [dpa99c/cordova-plugin-firebasex#94]
# Bug report

Cordova@9 (lib 9.0.1)
Android@8.0.0
Firebasex@6.0.6

Tested on device Android@6.0.1

When adding the notification icon xml into the config.xml, the app crashes at start. Removing the notification icon from the config.xml & rebuilding the app fixes it.

`<resource-file src="res/android/drawable-mdpi/notification_icon.png" target="app/src/main/res/drawable-mdpi/notification_icon.png" />
        <resource-file src="res/android/drawable-hdpi/notification_icon.png" target="app/src/main/res/drawable-hdpi/notification_icon.png" />
        <resource-file src="res/android/drawable-xhdpi/notification_icon.png" target="app/src/main/res/drawable-xhdpi/notification_icon.png" />
        <resource-file src="res/android/drawable-xxhdpi/notification_icon.png" target="app/src/main/res/drawable-xxhdpi/notification_icon.png" />
        <resource-file src="res/android/drawable-xxxhdpi/notification_icon.png" target="app/src/main/res/drawable-xxxhdpi/notification_icon.png" />
        <config-file target="AndroidManifest.xml" parent="application">
            <meta-data android:name="com.google.firebase.messaging.default_notification_icon" android:resource="@drawable/notification_icon" />
        </config-file>`

No build error whatsoever. All PNGs generated from [this page](https://romannurik.github.io/AndroidAssetStudio/icons-notification.html#source.type=clipart&source.clipart=ac_unit&source.space.trim=1&source.space.pad=0&name=ic_stat_ac_unit) and renamed to notification_icon.png

**Comment by dpa99c** [comment]
As highlighted in #85, there is a bug in `cordova@9` which means using `<config-file>` blocks in `config.xml` has unforeseen results.
As suggested in that issue, try adding [cordova-custom-config](https://github.com/dpa99c/cordova-custom-config) to the project and using its `<custom-config-file>` block in `config.xml` instead of `<config-file>`. This is the [workaround used in the example project](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/config.xml#L40).

**Comment by globules-io** [comment]
ok I will try that, thank you for you response
